config/routes.rb
Rails.application.routes.draw do
  
  root  "write_places#index"
  resources :write_places
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :write_places
end

app/models/write_place.rb
class WritePlace < ActiveRecord::Base
  has_one :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :password)
    end
end

app/controllers/write_places_controller.rb
class WritePlacesController < ApplicationController
  before_action :set_write_place, only: [:show, :edit, :update, :destroy]

  # GET /write_places
  # GET /write_places.json
  def index
    @write_places = WritePlace.all
  end

  # GET /write_places/1
  # GET /write_places/1.json
  def show
  end

  # GET /write_places/new
  def new
    @write_place = WritePlace.new
  end

  # GET /write_places/1/edit
  def edit
  end

  # POST /write_places
  # POST /write_places.json
  def create
    @write_place = WritePlace.new(write_place_params)

    respond_to do |format|
      if @write_place.save
        format.html { redirect_to @write_place, notice: 'Write place was successfully created.' }
        format.json { render :show, status: :created, location: @write_place }
      else
        format.html { render :new }
        format.json { render json: @write_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /write_places/1
  # PATCH/PUT /write_places/1.json
  def update
    respond_to do |format|
      if @write_place.update(write_place_params)
        format.html { redirect_to @write_place, notice: 'Write place was successfully updated.' }
        format.json { render :show, status: :ok, location: @write_place }
      else
        format.html { render :edit }
        format.json { render json: @write_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /write_places/1
  # DELETE /write_places/1.json
  def destroy
    @write_place.destroy
    respond_to do |format|
      format.html { redirect_to write_places_url, notice: 'Write place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_write_place
      @write_place = WritePlace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def write_place_params
      params.require(:write_place).permit(:name, :date, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/write_places_helper.rb
module WritePlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dairy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/write_places/_form.html.erb
<%= form_for(@write_place) do |f| %>
  <% if @write_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@write_place.errors.count, "error") %> prohibited this write_place from being saved:</h2>

      <ul>
      <% @write_place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/write_places/edit.html.erb
<h1>Editing write_place</h1>

<%= render 'form' %>

<%= link_to 'Show', @write_place %> |
<%= link_to 'Back', write_places_path %>

app/views/write_places/index.html.erb
<h1>Listing write_places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @write_places.each do |write_place| %>
      <tr>
        <td><%= write_place.name %></td>
        <td><%= write_place.date %></td>
        <td><%= write_place.text %></td>
        <td><%= link_to 'Show', write_place %></td>
        <td><%= link_to 'Edit', edit_write_place_path(write_place) %></td>
        <td><%= link_to 'Destroy', write_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Write place', new_write_place_path %>

app/views/write_places/new.html.erb
<h1>New write_place</h1>

<%= render 'form' %>

<%= link_to 'Back', write_places_path %>

app/views/write_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @write_place.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @write_place.date %>
</p>

<p>
  <strong>Text:</strong>
  <%= @write_place.text %>
</p>

<%= link_to 'Edit', edit_write_place_path(@write_place) %> |
<%= link_to 'Back', write_places_path %>